const EMAIL_ARTWORK_ROOT = '/examples/email-lifecycle';
const EMAIL_CARD_ROOT = `${EMAIL_ARTWORK_ROOT}/cards`;

const EMAIL_SUPPORTING_CARD_LIBRARY = {
  context: {
    body: 'Group related copy so translators can preserve meaning across every surface.',
    imageBackgroundColor: '#F5F1FB',
    imagePath: `${EMAIL_CARD_ROOT}/context-groups-language-panel.png`,
    title: 'Add translation context',
  },
  dashboard: {
    body: 'Review locales, activity, and translation quality from one workspace.',
    imageBackgroundColor: '#EEF4FA',
    imagePath: `${EMAIL_CARD_ROOT}/dashboard-language-panel.png`,
    title: 'Open the dashboard',
  },
  discord: {
    body: 'Meet other teams shipping multilingual products and get help from the community.',
    imageBackgroundColor: '#F0F1FB',
    imagePath: `${EMAIL_CARD_ROOT}/discord-language-panel.png`,
    title: 'Join the community',
  },
  github: {
    body: 'Follow the Quickstart or hand the same setup instructions to your coding agent.',
    imageBackgroundColor: '#F3F3EF',
    imagePath: `${EMAIL_CARD_ROOT}/github-language-panel.png`,
    title: 'Add GT to your stack',
  },
  locadex: {
    body: 'Let Locadex open localization pull requests and keep translations moving with code.',
    imageBackgroundColor: '#EFF5F2',
    imagePath: `${EMAIL_CARD_ROOT}/locadex-language-panel.png`,
    title: 'Let Locadex open the PR',
  },
} as const;

export type EmailLifecycleSupportingCard =
  (typeof EMAIL_SUPPORTING_CARD_LIBRARY)[keyof typeof EMAIL_SUPPORTING_CARD_LIBRARY];

const SUPPORTING_CARDS_BY_TEMPLATE: Readonly<
  Partial<Record<string, readonly EmailLifecycleSupportingCard[]>>
> = {
  'onboarding-day3-api-key-email': [EMAIL_SUPPORTING_CARD_LIBRARY.github],
  'onboarding-day3-live-email': [
    EMAIL_SUPPORTING_CARD_LIBRARY.context,
    EMAIL_SUPPORTING_CARD_LIBRARY.locadex,
    EMAIL_SUPPORTING_CARD_LIBRARY.dashboard,
  ],
  'onboarding-day6-api-key-email': [EMAIL_SUPPORTING_CARD_LIBRARY.github],
  'onboarding-day6-live-email': [
    EMAIL_SUPPORTING_CARD_LIBRARY.locadex,
    EMAIL_SUPPORTING_CARD_LIBRARY.context,
    EMAIL_SUPPORTING_CARD_LIBRARY.dashboard,
  ],
  'welcome-email': [
    EMAIL_SUPPORTING_CARD_LIBRARY.github,
    EMAIL_SUPPORTING_CARD_LIBRARY.discord,
    EMAIL_SUPPORTING_CARD_LIBRARY.locadex,
  ],
};

const EMAIL_LIFECYCLE_TEMPLATE_DEFINITIONS = [
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-welcome.gif`,
    body: "You're in. Choose a starting point below, or open your dashboard to create your first project.",
    cta: 'Open Dashboard',
    description: 'The account-creation welcome with a multilingual morph and three clear setup paths.',
    group: 'Welcome',
    id: 'welcome-email',
    keywords: ['welcome', 'signup', 'onboarding', 'dashboard', 'gif'],
    name: 'Welcome email',
    subject: 'Welcome to General Translation',
    symbol: '01',
    timing: 'Immediately after signup',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-start.gif`,
    body: 'Your first translation is about five minutes away. Complete setup in the dashboard, then run the Quickstart.',
    cta: 'Open Dashboard',
    description: 'Onboarding for a workspace that has not created an API key yet.',
    group: 'Onboarding',
    id: 'onboarding-day3-no-api-key-email',
    keywords: ['onboarding', 'no api key', 'quickstart', 'start'],
    name: 'Start setup',
    subject: 'Your first translation is 5 minutes away',
    symbol: '↗',
    timing: 'No API key',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-translate.gif`,
    body: 'Your API key is ready. Choose a path below to translate your first string.',
    cta: 'Run the Quickstart',
    description: 'Onboarding for a workspace with an API key but no translation.',
    group: 'Onboarding',
    id: 'onboarding-day3-api-key-email',
    keywords: ['onboarding', 'api key', 'translation', 'quickstart'],
    name: 'Translate',
    subject: "You're one step from your first translation",
    symbol: '文',
    timing: 'API key ready',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-live.gif`,
    body: 'Your first translation is live. Here are three ways to keep quality high and updates moving.',
    cta: 'Open Dashboard',
    description: 'Guidance for a workspace with a live translation or Locadex run.',
    group: 'Onboarding',
    id: 'onboarding-day3-live-email',
    keywords: ['onboarding', 'activated', 'live', 'translation'],
    name: 'Translation live',
    subject: 'Your first translation is live',
    symbol: '✓',
    timing: 'Activated',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-start.gif`,
    body: 'Still want to try it? Complete setup in the dashboard, then run the Quickstart.',
    cta: 'Continue setup',
    description: 'A lightweight reminder when setup has not started.',
    group: 'Onboarding',
    id: 'onboarding-day5-no-api-key-email',
    keywords: ['onboarding', 'reminder', 'no api key', 'start'],
    name: 'Setup reminder',
    subject: 'Still here if you want a hand',
    symbol: '↗',
    timing: 'Setup incomplete',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-translate.gif`,
    body: "Your API key is ready, but you haven't run a translation yet. Choose a path below and you'll be live in minutes.",
    cta: 'Translate your app',
    description: 'Activation guidance for a configured workspace without a translation.',
    group: 'Onboarding',
    id: 'onboarding-day6-api-key-email',
    keywords: ['onboarding', 'api key', 'translation', 'activate'],
    name: 'First translation',
    subject: 'Translate your app in 5 minutes',
    symbol: 'A',
    timing: 'Translation pending',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-live.gif`,
    body: "You're up and running. These three settings make localization easier to scale.",
    cta: 'Explore your workspace',
    description: 'Product guidance for an activated team ready to scale localization.',
    group: 'Onboarding',
    id: 'onboarding-day6-live-email',
    keywords: ['onboarding', 'activated', 'scale', 'locadex'],
    name: 'Activated guidance',
    subject: 'Getting the most out of General Translation',
    symbol: '✓',
    timing: 'Localization active',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-credits.gif`,
    body: "Thanks for finishing setup. Your translation credits are ready, and you won't be charged until you choose to buy more.",
    cta: 'Start translating',
    description: 'A confirmation that rewards completed billing setup with translation credits.',
    group: 'Onboarding',
    id: 'onboarding-payment-confirmation-email',
    keywords: ['onboarding', 'payment', 'confirmation', 'credits', 'billing'],
    name: 'Payment confirmation',
    subject: '$10 in translation credits is ready.',
    symbol: '$',
    timing: 'After payment setup',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-auth.gif`,
    body: 'Use the secure link below to sign in to General Translation. The link expires in 24 hours.',
    cta: 'Sign in',
    description: 'A restrained authentication email for a time-limited sign-in link.',
    group: 'Authentication',
    id: 'auth-magic-link-email',
    keywords: ['auth', 'magic link', 'sign in', 'transactional', '24 hours'],
    name: 'Magic link',
    subject: 'Your sign-in link for General Translation',
    symbol: '↗',
    timing: 'On sign-in request',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-auth.gif`,
    body: 'Taylor invited you to join the Acme organization on General Translation. This invitation expires in 7 days.',
    cta: 'Accept invitation',
    description: 'A recognizable membership invitation with a direct acceptance action.',
    group: 'Authentication',
    id: 'membership-invitation-email',
    keywords: ['invitation', 'membership', 'organization', 'transactional', '7 days'],
    name: 'Organization invitation',
    subject: "You've been invited to join Acme on General Translation",
    symbol: '+',
    timing: 'On invite or resend',
  },
  {
    artworkPath: null,
    body: "I'd love to help your team translate your product. General Translation is the full-stack localization platform for shipping in over 120 languages.",
    cta: '',
    description: 'A natural plain-text introduction from Archie for a qualified enterprise lead.',
    group: 'Enterprise',
    id: 'enterprise-intro-email',
    keywords: ['enterprise', 'sales', 'intro', 'plain text', 'archie'],
    name: 'Enterprise introduction',
    subject: 'General Translation Intro',
    symbol: 'E',
    timing: 'Qualified lead',
  },
  {
    artworkPath: null,
    body: 'Following up on my note about helping your team translate your app into any language. Happy to walk you through your localization stack.',
    cta: '',
    description: 'The first plain-text reply in the enterprise introduction thread.',
    group: 'Enterprise',
    id: 'enterprise-day3-follow-up-email',
    keywords: ['enterprise', 'sales', 'follow up', 'plain text', 'thread'],
    name: 'Enterprise follow-up',
    subject: 'General Translation Intro',
    symbol: '↗',
    timing: 'Follow-up',
  },
  {
    artworkPath: null,
    body: "Last email from me for now. If you'd like to talk through localization at any point, feel free to reach out whenever it's helpful.",
    cta: '',
    description: 'The final plain-text reply in the enterprise introduction thread.',
    group: 'Enterprise',
    id: 'enterprise-day7-follow-up-email',
    keywords: ['enterprise', 'sales', 'follow up', 'plain text', 'thread'],
    name: 'Enterprise final follow-up',
    subject: 'General Translation Intro',
    symbol: '✓',
    timing: 'Final follow-up',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-billing.gif`,
    body: 'Auto-reload is off. Add credits now, or turn it on to keep translations running without interruption.',
    cta: 'Add credits',
    description: 'A soft warning when the account has used most of its credit balance.',
    group: 'Billing',
    id: 'balance-soft-limit-email',
    keywords: ['billing', 'balance', 'soft limit', 'credits', 'warning'],
    name: 'Credit balance warning',
    subject: 'Your credit balance is running low.',
    symbol: '80',
    timing: '80% of balance used',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-billing-alert.gif`,
    body: 'Your credit balance is depleted. Add credits to resume translations now, or turn on auto-reload to avoid another interruption.',
    cta: 'Add credits',
    description: 'A hard-stop alert when a depleted credit balance pauses translations.',
    group: 'Billing',
    id: 'balance-hard-limit-email',
    keywords: ['billing', 'balance', 'hard limit', 'credits', 'paused'],
    name: 'Credit balance depleted',
    subject: 'Translations are paused.',
    symbol: '!',
    timing: 'Balance reaches zero',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-billing.gif`,
    body: "When you reach 100%, new translations will pause. Add a card to switch to usage-based billing with no monthly fee.",
    cta: 'Add payment method',
    description: 'A soft warning when a new workspace has nearly exhausted its free credits.',
    group: 'Billing',
    id: 'free-credit-soft-limit-email',
    keywords: ['billing', 'free credits', 'soft limit', 'payment method'],
    name: 'Free credit warning',
    subject: "You've used 80% of your free credits.",
    symbol: '80',
    timing: '80% of free credits used',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-billing-alert.gif`,
    body: "Your free credits are exhausted. Add a card to resume immediately with usage-based billing; there's no monthly fee.",
    cta: 'Add payment method',
    description: 'A hard-stop alert when free credits are exhausted and translations pause.',
    group: 'Billing',
    id: 'free-credit-hard-limit-email',
    keywords: ['billing', 'free credits', 'hard limit', 'paused'],
    name: 'Free credits exhausted',
    subject: 'Your translations are paused.',
    symbol: '!',
    timing: 'Free credits exhausted',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-usage.gif`,
    body: 'At 100%, new translations will pause until the limit resets or you raise it. Review the cap now to avoid interruption.',
    cta: 'Review usage limit',
    description: 'A soft warning when usage approaches the account cap.',
    group: 'Billing',
    id: 'usage-soft-limit-email',
    keywords: ['billing', 'usage', 'soft limit', 'cap', 'warning'],
    name: 'Usage limit warning',
    subject: "You're nearing your usage limit.",
    symbol: '80',
    timing: '80% of usage cap',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-usage.gif`,
    body: 'Your usage limit has been reached. Raise or remove your cap to resume now, or wait for the reset.',
    cta: 'Update usage limit',
    description: 'A hard-stop alert when the account reaches its usage cap.',
    group: 'Billing',
    id: 'usage-hard-limit-email',
    keywords: ['billing', 'usage', 'hard limit', 'cap', 'paused'],
    name: 'Usage limit reached',
    subject: 'Translations are paused.',
    symbol: '!',
    timing: 'Usage cap reached',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-billing-alert.gif`,
    body: "We couldn't charge the card on file for your recent usage. Update your payment method to keep translations running.",
    cta: 'Update payment method',
    description: 'An operational alert after a failed usage payment.',
    group: 'Billing',
    id: 'billing-payment-failed-email',
    keywords: ['billing', 'payment failed', 'card', 'alert'],
    name: 'Payment failed',
    subject: "Your payment didn't go through.",
    symbol: '!',
    timing: 'After failed payment',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-billing-alert.gif`,
    body: "We couldn't collect a recent usage charge, so your account moved back to the free plan. Your projects and translations are safe.",
    cta: 'Fix billing',
    description: 'A plan-state alert after billing is canceled or cannot be collected.',
    group: 'Billing',
    id: 'billing-plan-canceled-email',
    keywords: ['billing', 'plan canceled', 'free plan', 'alert'],
    name: 'Plan canceled',
    subject: 'Your account moved to the free plan.',
    symbol: '!',
    timing: 'After plan cancellation',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-credits.gif`,
    body: 'Your payment method is saved and usage-based billing is on. Choose your framework in the docs to start translating.',
    cta: 'Go to Docs',
    description: 'A confirmation that a paid plan and usage-based billing are active.',
    group: 'Billing',
    id: 'upgrade-confirmation-email',
    keywords: ['billing', 'upgrade', 'plan active', 'credits', 'confirmation'],
    name: 'Plan activated',
    subject: 'Your Starter plan is active.',
    symbol: '✓',
    timing: 'After plan activation',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-locadex.gif`,
    body: 'Locadex finished setting up your project for automated localization. Review and merge the setup PR to turn it on.',
    cta: 'Review the PR',
    description: 'A product email confirming that the Locadex setup pull request is ready.',
    group: 'Locadex',
    id: 'locadex-setup-complete-email',
    keywords: ['locadex', 'setup', 'pull request', 'github', 'automation'],
    name: 'Locadex setup complete',
    subject: 'Your Locadex setup PR is ready.',
    symbol: 'PR',
    timing: 'After setup PR opens',
  },
  {
    artworkPath: `${EMAIL_ARTWORK_ROOT}/email-header-locadex.gif`,
    body: 'Locadex opened a pull request with the latest translations. Review and merge it to keep your app fully translated.',
    cta: 'Review the PR',
    description: 'A reminder that an open Locadex translation pull request is waiting for review.',
    group: 'Locadex',
    id: 'locadex-pr-reminder-email',
    keywords: ['locadex', 'reminder', 'pull request', 'github', 'translations'],
    name: 'Locadex PR reminder',
    subject: 'Your latest translations are ready.',
    symbol: 'PR',
    timing: '24 hours after PR opens',
  },
] as const;

export const EMAIL_LIFECYCLE_TEMPLATES = EMAIL_LIFECYCLE_TEMPLATE_DEFINITIONS.map(
  (template) => ({
    ...template,
    supportingCards: SUPPORTING_CARDS_BY_TEMPLATE[template.id] ?? [],
  })
);

export function getEmailLifecycleTemplate(elementId: string) {
  return EMAIL_LIFECYCLE_TEMPLATES.find(({ id }) => id === elementId);
}
