import type {
  BrandApplication,
  BrandAsset,
  BrandFontAsset,
  BrandIdentity,
} from './brandIdentity';

const REVISION = 7;

function asset(
  id: string,
  label: string,
  path: string,
  surface: BrandAsset['surface'],
  type: BrandAsset['type'] = 'logo'
): BrandAsset {
  return { id, label, path, surface, type };
}

function application(
  id: string,
  name: string,
  category: BrandApplication['category'],
  format: string,
  description: string
): BrandApplication {
  return { category, description, format, id, name };
}

const GT_FONT_ASSETS: BrandFontAsset[] = [
  {
    family: 'Switzer',
    fileName: 'Switzer-Regular.ttf',
    format: 'truetype',
    id: 'switzer-400',
    label: 'Switzer Regular',
    path: '/fonts/switzer-400.ttf',
    style: 'normal',
    weight: 400,
  },
  {
    family: 'Switzer',
    fileName: 'Switzer-Medium.ttf',
    format: 'truetype',
    id: 'switzer-500',
    label: 'Switzer Medium',
    path: '/fonts/switzer-500.ttf',
    style: 'normal',
    weight: 500,
  },
  {
    family: 'Geist Mono',
    fileName: 'GeistMono-Variable.ttf',
    format: 'truetype',
    id: 'geist-mono-variable',
    label: 'Geist Mono Variable',
    path: '/fonts/geist-mono-variable.ttf',
    style: 'normal',
    weight: 400,
    weightMax: 900,
    weightMin: 100,
  },
];

export const GT_BRAND_IDENTITY: BrandIdentity = {
  applications: [
    application('identity', 'Identity thesis', 'foundation', '1600 × 1000', 'The GT mark, multilingual promise, and source-of-truth idea in one opening composition.'),
    application('logo-family', 'Logo family', 'foundation', 'Responsive system', 'Mark, banner, wordmark, product lockups, and strict black-or-white surface behavior.'),
    application('language-motion', 'Language morph', 'marketing', 'GIF / video', 'Centered greetings move between writing systems with a short cubic-bezier morph fade.'),
    application('welcome-email', 'Welcome email', 'marketing', '640 px / responsive', 'A spare onboarding email that introduces the platform through language, product paths, and community.'),
    application('cli', 'Developer CLI', 'developer', '80 columns', 'Commands, locale state, diffs, and Locadex handoff rendered as a credible developer surface.'),
    application('product', 'Localization workspace', 'product', '1440 × 1024', 'Repository context, translation status, review state, and delivery are treated as one system.'),
    application('editorial', 'Engineering story', 'editorial', '1600 × 900', 'A high-contrast editorial cover pairing multilingual type with code-level detail.'),
    application('event', 'Global product pass', 'event', 'CR80 / lanyard', 'A monochrome attendee system whose variable field is language rather than decoration.'),
    application('social', 'Launch sequence', 'social', '1:1 / 16:9', 'Repeatable announcements built from locale metadata, open space, and centered language transitions.'),
    application('docs', 'Documentation header', 'developer', '1440 × 480', 'A technical masthead connecting framework packages, commands, and implementation guides.'),
  ],
  assets: [
    asset('mark-dark', 'Black GT mark', '/brands/gt/logos/mark-black.svg', 'light'),
    asset('mark-light', 'White GT mark', '/brands/gt/logos/mark-white.svg', 'dark'),
    asset('banner', 'GT banner', '/brands/gt/logos/banner-black.svg', 'light'),
    asset('wordmark', 'General Translation wordmark', '/brands/gt/logos/wordmark-black.svg', 'light'),
    asset('wordmark-light', 'General Translation white wordmark', '/brands/gt/logos/wordmark-white.svg', 'dark'),
    asset('locadex', 'Locadex wordmark', '/brands/gt/logos/locadex-black.svg', 'light', 'product'),
    asset('identity-field', 'GT translation field', '/brands/gt/assets/translation-field.svg', 'any', 'background'),
  ],
  audiences: ['Product engineers', 'Localization teams', 'Developer-first companies', 'AI-native product teams'],
  builtIn: true,
  colors: [
    { hex: '#181818', id: 'ink', name: 'Ink', role: 'Primary type, marks, and dark surfaces' },
    { hex: '#FFFFFF', id: 'paper', name: 'Paper', role: 'Primary light surface and reversed type' },
    { hex: '#F4F4F4', id: 'muted', name: 'Mist', role: 'Quiet product and editorial surfaces' },
    { hex: '#E4E4E4', id: 'emphasis', name: 'Silver', role: 'Selection, focus, dividers, and metadata' },
    { hex: '#D4D4D4', id: 'success', name: 'Cloud', role: 'Completed and healthy states' },
    { hex: '#A3A3A3', id: 'warning', name: 'Slate', role: 'Attention, secondary type, and disabled states' },
    { hex: '#525252', id: 'progress', name: 'Graphite', role: 'Active work and in-progress states' },
    { hex: '#262626', id: 'error', name: 'Charcoal', role: 'Destructive actions without introducing chroma' },
  ],
  contactEmail: 'hello@generaltranslation.com',
  description: 'A black-and-white developer identity for a localization framework that keeps code, product copy, documentation, review, and delivery in one source-of-truth workflow.',
  greetings: ['Welcome', 'Bienvenidos', '你好', 'ようこそ', 'أهلاً وسهلاً'],
  fonts: GT_FONT_ASSETS,
  graphicSystem: {
    composition: 'Centered language is the hero. Code, locale labels, and product evidence align to a calm modular field around it.',
    description: 'The language field turns a changing string into a stable brand device: language transforms while the surrounding system remains quiet and precise.',
    device: 'The translation frame',
    imageDirection: 'Monochrome crops, interface evidence, terminal output, and multilingual specimens. No generic globe imagery or flags.',
    pattern: 'grid',
    rules: ['Black and white through and through', 'Center morphing language optically, not mathematically only', 'Use locale metadata and whitespace as structure', 'Never layer duplicate display text', 'Let product evidence carry the visual interest'],
  },
  id: 'gt',
  kind: 'example',
  mission: 'Make every product feel native in every language without disconnecting content from code.',
  motion: [
    { curve: 'cubic-bezier(0.4, 0, 0.2, 1)', description: 'Fast centered language morph with a one-second word hold.', durationMs: 1000, id: 'morph-1000', name: 'Morph / 1.00 s', previewPath: '/examples/gt-morph-one-second.gif' },
    { curve: 'cubic-bezier(0.4, 0, 0.2, 1)', description: 'The default centered morph cadence for brand introductions.', durationMs: 1250, id: 'morph-1250', name: 'Morph / 1.25 s', previewPath: '/examples/gt-morph.gif' },
    { curve: 'cubic-bezier(0.4, 0, 0.2, 1)', description: 'A more spacious morph for hero and presentation surfaces.', durationMs: 1500, id: 'morph-1500', name: 'Morph / 1.50 s', previewPath: '/examples/gt-morph-fast.gif' },
    { curve: 'cubic-bezier(0.4, 0, 0.2, 1)', description: 'Letter-by-letter typing and deletion without a cursor.', durationMs: 1750, id: 'type-delete', name: 'Type + delete', previewPath: '/examples/gt-type-delete.gif' },
  ],
  name: 'General Translation',
  positioning: 'GT is the internationalization infrastructure for teams that want product language to move with their code—from authoring and context to review, automation, and delivery.',
  products: ['Internationalization', 'Translation', 'Locadex', 'CDN delivery'],
  proof: ['Cursor', 'Cognition', 'Windsurf', 'Ramp', 'Mintlify', 'ClickHouse'],
  proofAssets: [
    asset('cursor', 'Cursor', '/brands/gt/proof/cursor.svg', 'light', 'proof'),
    asset('ramp', 'Ramp', '/brands/gt/proof/ramp.svg', 'light', 'proof'),
    asset('mintlify', 'Mintlify', '/brands/gt/proof/mintlify.svg', 'light', 'proof'),
    asset('clickhouse', 'ClickHouse', '/brands/gt/proof/clickhouse.svg', 'light', 'proof'),
    asset('windsurf', 'Windsurf', '/brands/gt/proof/windsurf.svg', 'light', 'proof'),
  ],
  revision: REVISION,
  shortName: 'GT',
  socialHandle: '@generaltranslation',
  sourceNotes: ['GT product and landing applications', 'GT package, CLI, Locadex, and onboarding language', 'Black-and-white interface tokens and component behavior', 'Multilingual email motion studies created in Glyphfield'],
  strategy: {
    challenge: 'Localization is usually fragmented across string files, vendors, spreadsheets, product surfaces, and late review—separating language from the code and context that give it meaning.',
    concept: 'One source of truth, expressed as one stable frame through which every language can move.',
    outcome: 'A technical identity that feels native to engineering workflows while making multilingual change visible, legible, and memorable.',
    personality: ['Exact', 'Global', 'Technical', 'Quietly confident'],
    pillars: ['Language stays connected to code', 'Context travels with every string', 'Automation remains reviewable', 'Every locale is a first-class product surface'],
    promise: 'Ship every language with the same confidence as the source language.',
  },
  style: { borderRadius: 0, density: 'comfortable', grid: 'none', imageTreatment: 'monochrome', logoScale: 100 },
  tagline: 'One source of truth. Every language.',
  typography: [
    { family: 'Switzer', fontId: 'switzer-500', letterSpacing: -0.2, lineHeight: 1.08, role: 'Display', usage: 'Open, measured headlines and product statements', weight: 500 },
    { family: 'Switzer', fontId: 'switzer-400', letterSpacing: 0.1, lineHeight: 1.62, role: 'Body', usage: 'Interface copy, documentation, email, and long-form explanation', weight: 400 },
    { family: 'Switzer', fontId: 'switzer-400', letterSpacing: 0.15, lineHeight: 1.36, role: 'Accent', usage: 'Multilingual specimens with optical centering by writing system', weight: 400 },
    { family: 'Geist Mono', fontId: 'geist-mono-variable', letterSpacing: 0.25, lineHeight: 1.5, role: 'Code', usage: 'Commands, locale codes, tokens, diffs, and technical metadata', weight: 400 },
  ],
  values: ['Source of truth', 'Context over strings', 'Developer agency', 'Global by default'],
  voice: {
    avoid: ['Abstract global-growth clichés', 'Unverifiable speed claims', 'Translation language detached from developer workflow'],
    phrases: ['Code is the source of truth.', 'Language moves with the product.', 'Let Locadex open the PR.'],
    principles: ['Developer-first', 'Direct and concrete', 'Technically credible', 'Globally aware'],
  },
  website: 'generaltranslation.com',
};

export const TEMPLATE_BRAND_IDENTITY: BrandIdentity = {
  applications: [
    application('thesis', 'Brand thesis', 'foundation', '1600 × 1000', 'Define the problem, promise, concept, and recognizable device before decorating outputs.'),
    application('logo', 'Logo architecture', 'foundation', 'Responsive family', 'Map mark, wordmark, lockups, clear space, minimum size, and surface variants.'),
    application('system', 'Graphic system', 'foundation', 'Repeatable rules', 'Turn one strategic idea into composition, pattern, image, motion, and hierarchy rules.'),
    application('product', 'Product surface', 'product', 'Responsive', 'Prove the identity at real interface density instead of only on posters.'),
    application('campaign', 'Campaign system', 'marketing', '1:1 / 4:5 / 16:9', 'Show how one message adapts without losing the identity.'),
    application('editorial', 'Editorial story', 'editorial', '1600 × 900', 'Test long-form pacing, pull quotes, captions, and image behavior.'),
    application('social', 'Social sequence', 'social', '1:1 / 9:16', 'A repeatable family of launches, proof points, and product updates.'),
    application('physical', 'Physical touchpoint', 'physical', 'Print-ready', 'Prove the system survives material, scale, production, and distance.'),
  ],
  assets: [
    asset('mark-dark', 'Template dark mark', '/templates/logos/template-mark.svg', 'light'),
    asset('mark-light', 'Template light mark', '/templates/logos/template-mark-white.svg', 'dark'),
    asset('wordmark', 'Template wordmark', '/templates/logos/template-wordmark.svg', 'light'),
    asset('wordmark-light', 'Template white wordmark', '/templates/logos/template-wordmark-white.svg', 'dark'),
    asset('identity-field', 'Template construction field', '/templates/assets/template-field.svg', 'any', 'background'),
  ],
  audiences: ['Primary decision-maker', 'Daily user', 'Internal champion', 'Wider culture'],
  builtIn: true,
  colors: [
    { hex: '#111318', id: 'ink', name: 'Core dark', role: 'Primary type and high-contrast surfaces' },
    { hex: '#FFFFFF', id: 'paper', name: 'Core light', role: 'Primary background and reversed type' },
    { hex: '#F0F2F5', id: 'muted', name: 'Quiet', role: 'Secondary surfaces and layout testing' },
    { hex: '#2F6BFF', id: 'emphasis', name: 'Primary', role: 'Replace with the brand-defining chroma' },
    { hex: '#B9FF66', id: 'success', name: 'Secondary', role: 'Replace with a supporting color role' },
    { hex: '#FF5C7A', id: 'warning', name: 'Accent', role: 'Use sparingly for contrast and pacing' },
    { hex: '#677084', id: 'progress', name: 'Midtone', role: 'Metadata, secondary type, and diagrams' },
    { hex: '#222630', id: 'error', name: 'Deep', role: 'Dark extension of the primary system' },
  ],
  contactEmail: 'hello@brand.com',
  description: 'A rigorous identity blueprint organized around strategy, a recognizable graphic idea, reusable foundations, motion, voice, and applications.',
  greetings: ['Brand', 'System', 'Application'],
  graphicSystem: {
    composition: 'Use the modular field to test scale, hierarchy, tension, and repetition before choosing a signature composition.',
    description: 'A visible construction field keeps placeholders honest and exposes where the final identity still needs a deliberate rule.',
    device: 'The construction field',
    imageDirection: 'Replace every placeholder with purposeful subject, crop, treatment, and caption behavior.',
    pattern: 'grid',
    rules: ['Start from the strategic concept', 'Define one recognizable graphic device', 'Test every rule at product and campaign density', 'Document what changes and what remains invariant'],
  },
  id: 'template',
  kind: 'template',
  mission: 'Turn a brand idea into a system another person can apply consistently.',
  motion: [],
  name: 'Template',
  positioning: 'A complete identity framework for moving from strategic premise to a useful, repeatable, and exportable brand system.',
  products: ['Foundations', 'Expression', 'Product', 'Campaign'],
  proof: ['Strategy', 'Recognition', 'Consistency', 'Range'],
  proofAssets: [],
  revision: REVISION,
  shortName: 'TM',
  socialHandle: '@brand',
  sourceNotes: ['Structured from identity case-study anatomy', 'Duplicate before editing', 'Replace guidance copy with evidence from the brand'],
  strategy: {
    challenge: 'State the business or cultural problem the identity must solve—not the visual symptom.',
    concept: 'Name the single idea that can organize logo, type, color, imagery, motion, product, and campaign behavior.',
    outcome: 'Describe how the new system should change recognition, trust, conversion, usability, or organizational consistency.',
    personality: ['Trait one', 'Trait two', 'Trait three', 'Trait four'],
    pillars: ['Strategic pillar one', 'Strategic pillar two', 'Strategic pillar three', 'Strategic pillar four'],
    promise: 'Write the durable promise a user should be able to feel in every touchpoint.',
  },
  style: { borderRadius: 8, density: 'comfortable', grid: 'none', imageTreatment: 'natural', logoScale: 100 },
  tagline: 'From premise to pattern to proof.',
  typography: [
    { family: 'Switzer', role: 'Display', usage: 'Replace with the expressive headline family and define scale behavior' },
    { family: 'Switzer', role: 'Body', usage: 'Replace with the durable reading and interface family' },
    { family: 'Instrument Serif', role: 'Accent', usage: 'Optional contrast for editorial moments, quotes, or product naming' },
    { family: 'Geist Mono', role: 'Code', usage: 'Specifications, tokens, metadata, diagrams, and technical applications' },
  ],
  values: ['Useful', 'Recognizable', 'Coherent', 'Expandable'],
  voice: { avoid: ['Generic superlatives', 'Unsupported claims', 'Tone without context'], phrases: ['Say the useful thing first.'], principles: ['Specific', 'Human', 'Consistent', 'Distinctive'] },
  website: 'brand.com',
};

export const STARTER_BRAND_IDENTITY: BrandIdentity = {
  ...TEMPLATE_BRAND_IDENTITY,
  applications: [
    application('identity', 'Starter identity', 'foundation', '1600 × 1000', 'A decisive opening composition built around the signal window.'),
    application('logo', 'Logo family', 'foundation', 'Responsive family', 'A compact spark mark, wordmark, and horizontal lockup.'),
    application('product', 'Workspace', 'product', '1440 × 1024', 'A focused planning surface with blue signal states and low-noise scaffolding.'),
    application('launch', 'Launch story', 'marketing', '16:9 / 4:5', 'One clear announcement scaled through the system.'),
    application('notes', 'Field notes', 'editorial', 'A4 / web', 'Research, decisions, and progress assembled as a living record.'),
    application('social', 'Progress cards', 'social', '1:1', 'Short updates that use the signal window as a consistent anchor.'),
    application('deck', 'Working deck', 'editorial', '16:9', 'A title, argument, evidence, system, and next-step slide family.'),
    application('kit', 'Team kit', 'physical', 'Notebook / card', 'Small-scale material applications that preserve the crisp window motif.'),
  ],
  assets: [
    asset('mark-dark', 'Starter black mark', '/templates/logos/starter-mark.svg', 'light'),
    asset('mark-light', 'Starter white mark', '/templates/logos/starter-mark-white.svg', 'dark'),
    asset('wordmark', 'Starter wordmark', '/templates/logos/starter-wordmark.svg', 'light'),
    asset('wordmark-light', 'Starter white wordmark', '/templates/logos/starter-wordmark-white.svg', 'dark'),
    asset('identity-field', 'Starter signal field', '/templates/assets/starter-field.svg', 'any', 'background'),
  ],
  audiences: ['Small product teams', 'Independent makers', 'Design-led founders', 'Internal innovation groups'],
  colors: [
    { hex: '#171A21', id: 'ink', name: 'Night', role: 'Primary text and decisive surfaces' },
    { hex: '#FFFFFF', id: 'paper', name: 'Paper', role: 'Open space and primary background' },
    { hex: '#EEF2F8', id: 'muted', name: 'Fog', role: 'Working surfaces and quiet structure' },
    { hex: '#2F6BFF', id: 'emphasis', name: 'Signal blue', role: 'Primary action, focus, and signature window' },
    { hex: '#CDE0FF', id: 'success', name: 'Sky', role: 'Positive state and soft blue field' },
    { hex: '#FFCB69', id: 'warning', name: 'Warm note', role: 'Annotations and moments requiring attention' },
    { hex: '#677084', id: 'progress', name: 'Slate', role: 'Secondary type and progress state' },
    { hex: '#20283A', id: 'error', name: 'Deep blue', role: 'Dark tonal extension and contrast' },
  ],
  contactEmail: 'hello@starter.studio',
  description: 'A complete but intentionally neutral starter identity for a small team turning research into a focused product direction.',
  greetings: ['Observe', 'Frame', 'Make'],
  graphicSystem: {
    composition: 'A blue signal window anchors one edge of each composition while notes, evidence, and decisions align to an open field.',
    description: 'The signal window is a frame for the one thing that matters now—an image, decision, metric, or next action.',
    device: 'The signal window',
    imageDirection: 'Natural research imagery, close crops, taped references, interface evidence, and candid work-in-progress details.',
    pattern: 'brackets',
    rules: ['One signal window per composition', 'Keep the rest of the field quiet', 'Use blue for focus, not decoration', 'Pair every claim with a note, artifact, or next step'],
  },
  id: 'starter',
  mission: 'Help small teams turn scattered observations into one clear direction they can build.',
  name: 'Starter',
  positioning: 'A lightweight research and planning workspace for teams who need clarity before they need more process.',
  products: ['Research board', 'Decision log', 'Working brief', 'Shareable review'],
  proof: ['Less noise', 'Clear ownership', 'Visible decisions', 'Faster alignment'],
  revision: REVISION,
  shortName: 'ST',
  socialHandle: '@starterstudio',
  sourceNotes: ['Complete example intended to be duplicated and renamed', 'All copy, colors, applications, and graphic rules are editable', 'Uses bundled template marks rather than a third-party identity'],
  strategy: {
    challenge: 'Early product work fragments across calls, screenshots, documents, and opinions before the team has agreed on what matters.',
    concept: 'Make the signal visible.',
    outcome: 'A calm working identity that helps a team recognize the important artifact, decision, and next move at a glance.',
    personality: ['Observant', 'Practical', 'Optimistic', 'Unfussy'],
    pillars: ['Collect real evidence', 'Frame the decision', 'Make ownership visible', 'Keep momentum legible'],
    promise: 'Find the signal and move the work forward.',
  },
  style: { borderRadius: 6, density: 'comfortable', grid: 'none', imageTreatment: 'natural', logoScale: 96 },
  tagline: 'Make the signal visible.',
  typography: [
    { family: 'Switzer', role: 'Display', usage: 'Direct headlines and compact product statements' },
    { family: 'Switzer', role: 'Body', usage: 'Working notes, interface copy, and brief narrative' },
    { family: 'Instrument Serif', role: 'Accent', usage: 'Observations, quotes, and editorial emphasis' },
    { family: 'Geist Mono', role: 'Code', usage: 'Dates, states, owners, versioning, and artifact metadata' },
  ],
  values: ['Evidence', 'Focus', 'Momentum', 'Care'],
  voice: { avoid: ['Strategy theater', 'Inflated certainty', 'Process for its own sake'], phrases: ['What did we learn?', 'What changed?', 'What happens next?'], principles: ['Observant', 'Plainspoken', 'Constructive', 'Decisive'] },
  website: 'starter.studio',
};

export const RAMP_BRAND_IDENTITY: BrandIdentity = {
  applications: [
    application('identity', 'Time is money', 'foundation', '1600 × 1000', 'A decisive identity composition connecting financial control to reclaimed time.'),
    application('logo', 'Ramp logo system', 'foundation', 'Symbol / wordmark / lockup', 'Official slate and white assets with generous clear space and no decorative recoloring.'),
    application('dashboard', 'Finance operations', 'product', '1440 × 1024', 'Cards, spend, approvals, bills, travel, accounting, and intelligence in one high-density operating view.'),
    application('savings', 'Savings proof', 'marketing', '16:9', 'Evidence-led campaign units that turn dollars and hours saved into the main visual.'),
    application('report', 'Finance benchmark', 'editorial', 'A4 / web', 'Data-rich editorial spreads for finance leaders with confident oversized numerals.'),
    application('card', 'Corporate card', 'physical', '85.60 × 53.98 mm', 'The logo and slate system applied to the most tangible product artifact.'),
    application('social', 'Operator stories', 'social', '1:1 / 4:5', 'Customer outcomes, product launches, and financial insights in a repeatable proof-first system.'),
    application('event', 'Finance forward', 'event', 'Stage / badge', 'Large-scale typography and ledger-like structures for finance and operator audiences.'),
  ],
  assets: [
    asset('mark-dark', 'Official Ramp symbol / slate', '/brands/ramp/logos/mark-slate.svg', 'light'),
    asset('mark-light', 'Official Ramp symbol / white', '/brands/ramp/logos/mark-white.svg', 'dark'),
    asset('wordmark', 'Official Ramp wordmark / slate', '/brands/ramp/logos/wordmark-slate.svg', 'light'),
    asset('wordmark-light', 'Official Ramp wordmark / white', '/brands/ramp/logos/wordmark-white.svg', 'dark'),
    asset('identity-field', 'Ramp economic field', '/brands/ramp/assets/economic-field.svg', 'any', 'background'),
  ],
  audiences: ['Finance leaders', 'Controllers and accountants', 'Operations teams', 'Employees spending on behalf of a business'],
  builtIn: true,
  colors: [
    { hex: '#292827', id: 'ink', name: 'Ramp slate', role: 'Official wordmark, primary type, and product contrast' },
    { hex: '#F8F7F3', id: 'paper', name: 'Warm paper', role: 'Editorial and campaign background' },
    { hex: '#E8E7E2', id: 'muted', name: 'Ledger', role: 'Product divisions and quiet information fields' },
    { hex: '#D7FF64', id: 'emphasis', name: 'Highlighter', role: 'Savings, action, and financial signal' },
    { hex: '#A7B5A6', id: 'success', name: 'Sage', role: 'Healthy business and positive movement' },
    { hex: '#F4C84A', id: 'warning', name: 'Statement yellow', role: 'Campaign emphasis and attention' },
    { hex: '#C96B45', id: 'progress', name: 'Rust', role: 'Editorial contrast and material warmth' },
    { hex: '#171716', id: 'error', name: 'Black slate', role: 'Deep campaign and product surfaces' },
  ],
  contactEmail: 'press@ramp.com',
  description: 'A proof-first identity for the finance operations platform built to save businesses time and money and free finance teams to focus on higher-value work.',
  greetings: ['Save time', 'Save money', 'Move faster'],
  graphicSystem: { composition: 'Large economic proof leads; interface details and ledger rules organize the supporting story.', description: 'The savings ledger converts financial operations into visible evidence: money, time, transactions, controls, and the work a team gets back.', device: 'The savings ledger', imageDirection: 'Confident product evidence, cards, operator portraits, and candid workplace imagery with warm editorial crops.', pattern: 'steps', rules: ['Lead with quantified customer value', 'Use the ledger to align evidence', 'Keep the official logo slate or white', 'Balance financial rigor with human time regained'] },
  id: 'ramp',
  kind: 'example',
  mission: 'Set finance free to build healthier businesses.',
  motion: [{ curve: 'cubic-bezier(0.22, 1, 0.36, 1)', description: 'Ledger rows advance, totals reconcile, and saved time accumulates with crisp financial confidence.', durationMs: 900, id: 'ledger-reconcile', name: 'Ledger reconcile', previewPath: '' }],
  name: 'Ramp',
  positioning: 'Ramp is the finance operations platform that brings cards, spend, payments, accounting, and intelligence together to save businesses their most valuable resources: time and money.',
  products: ['Corporate cards', 'Expense management', 'Accounts payable', 'Travel', 'Procurement', 'Treasury'],
  proof: ['70,000+ customers', '$12B+ saved', '27M+ hours eliminated', 'Books closed 8 days faster'],
  proofAssets: [],
  revision: REVISION,
  shortName: 'R',
  socialHandle: '@tryramp',
  sourceNotes: ['Official Ramp press page and 2026 press kit', 'Official Ramp slate and white logo archive', 'Current Ramp company positioning and published proof points'],
  strategy: { challenge: 'Finance teams lose strategic time to fragmented cards, reimbursements, bills, approvals, accounting work, and legacy systems designed to increase spend.', concept: 'Time is money—make both forms of savings visible.', outcome: 'A rigorous but energetic system that makes the value of finance automation immediately legible to executives and operators.', personality: ['Decisive', 'Economical', 'Modern', 'Operator-minded'], pillars: ['Save time', 'Save money', 'Automate the manual', 'Give finance control without friction'], promise: 'Ramp gives finance teams time back and makes every dollar work harder.' },
  style: { borderRadius: 2, density: 'compact', grid: 'none', imageTreatment: 'natural', logoScale: 94 },
  tagline: 'Time is money. Save both.',
  typography: [{ family: 'Ramp Sans', role: 'Display', usage: 'Oversized economic proof and editorial statements' }, { family: 'Inter', role: 'Body', usage: 'Product UI and explanatory copy' }, { family: 'Times New Roman', role: 'Accent', usage: 'Editorial contrast in reports and thought leadership' }, { family: 'Geist Mono', role: 'Code', usage: 'Amounts, dates, ledger states, and evidence labels' }],
  values: ['Grow without fear', 'Take ownership', 'We win when customers win', 'Amp it up'],
  voice: { avoid: ['Abstract fintech futurism', 'Benefits without quantified evidence', 'Complexity disguised as expertise'], phrases: ['Time is money. Save both.', 'Setting finance free.', 'Build healthier businesses.'], principles: ['Proof-first', 'Economical', 'Confident', 'Operator-aware'] },
  website: 'ramp.com',
};

export const MINTLIFY_BRAND_IDENTITY: BrandIdentity = {
  applications: [
    application('identity', 'The front door to your product', 'foundation', '1600 × 1000', 'The Mintlify sprout, green light, and an editorial documentation promise.'),
    application('logo', 'Mintlify logo family', 'foundation', 'Mark / wordmark', 'Green sprout mark with dark wordmark and clean light/dark handling.'),
    application('docs', 'Documentation home', 'product', '1440 × 1024', 'Navigation, search, cards, API reference, and AI assistance presented as one calm reading environment.'),
    application('api', 'API playground', 'developer', 'Responsive', 'Requests, responses, authentication, and examples balanced with readable documentation.'),
    application('themes', 'Theme gallery', 'marketing', '16:9', 'A family of product variations demonstrating opinionated defaults and deep customization.'),
    application('launch', 'Product launch', 'social', '1:1 / 4:5', 'Green beams and documentation frames reveal a new feature without losing product specificity.'),
    application('guide', 'Documentation guide', 'editorial', 'A4 / web', 'A practical long-form system for writing, organizing, and maintaining useful docs.'),
    application('conference', 'Developer desk', 'event', 'Booth / badge', 'A calm green environment built around real documentation and live product exploration.'),
  ],
  assets: [
    asset('mark-dark', 'Mintlify sprout mark', '/brands/mintlify/logos/mark.svg', 'light'),
    asset('mark-light', 'Mintlify sprout mark / light', '/brands/mintlify/logos/mark-light.svg', 'dark'),
    asset('wordmark', 'Mintlify wordmark', '/brands/mintlify/logos/wordmark.svg', 'light'),
    asset('wordmark-light', 'Mintlify white wordmark', '/brands/mintlify/logos/wordmark-light.svg', 'dark'),
    asset('identity-field', 'Mintlify documentation field', '/brands/mintlify/assets/docs-field.svg', 'any', 'background'),
  ],
  audiences: ['Developer experience teams', 'API teams', 'Technical writers', 'Product-led software companies'],
  builtIn: true,
  colors: [{ hex: '#0F172A', id: 'ink', name: 'Midnight', role: 'Primary type and dark surfaces' }, { hex: '#FFFFFF', id: 'paper', name: 'White', role: 'Reading surface' }, { hex: '#F4F7F6', id: 'muted', name: 'Mist', role: 'Documentation chrome and card fields' }, { hex: '#0D9373', id: 'emphasis', name: 'Mint', role: 'Primary action and navigation emphasis' }, { hex: '#55D799', id: 'success', name: 'Fresh mint', role: 'Dark-mode emphasis and positive state' }, { hex: '#B7F5DC', id: 'warning', name: 'Mint light', role: 'Soft accent fields and diagrams' }, { hex: '#64748B', id: 'progress', name: 'Slate', role: 'Secondary documentation type' }, { hex: '#071611', id: 'error', name: 'Forest', role: 'Deep green environment and contrast' }],
  contactEmail: 'support@mintlify.com',
  description: 'A calm, green, developer-first identity for beautiful documentation that is opinionated by default, flexible in practice, and effortless to read.',
  greetings: ['Read', 'Build', 'Understand'],
  graphicSystem: { composition: 'Documentation frames sit in generous fields while green beams guide attention from navigation to answer.', description: 'The knowledge beam makes information feel discoverable: a soft directional green field that illuminates the right page, component, or answer.', device: 'The knowledge beam', imageDirection: 'Crisp product screenshots, readable code, real API examples, and restrained dimensional green light.', pattern: 'rays', rules: ['The document remains the hero', 'Use green as a navigational light', 'Show real code and readable product UI', 'Keep customization visible without visual noise'] },
  id: 'mintlify',
  kind: 'example',
  mission: 'Help every team create documentation developers are proud to use.',
  motion: [{ curve: 'cubic-bezier(0.16, 1, 0.3, 1)', description: 'A soft beam reveals navigation, content, and the answer in a quick, natural sequence.', durationMs: 1100, id: 'knowledge-reveal', name: 'Knowledge reveal', previewPath: '' }],
  name: 'Mintlify',
  positioning: 'Mintlify is an intelligent documentation platform for creating, maintaining, and discovering product and API knowledge.',
  products: ['Documentation', 'API reference', 'AI assistant', 'Web editor', 'Themes', 'Analytics'],
  proof: ['Opinionated defaults', 'Flexible themes', 'MDX components', 'AI-native discovery'],
  proofAssets: [],
  revision: REVISION,
  shortName: 'M',
  socialHandle: '@mintlify',
  sourceNotes: ['Official Mintlify appearance and branding documentation', 'Mintlify design philosophy and dashboard redesign essays', 'Existing official Mintlify logo asset in the GT source set'],
  strategy: { challenge: 'Documentation becomes hard to navigate, expensive to maintain, visually disconnected from the product, and invisible to users who need an answer now.', concept: 'Illuminate the path to understanding.', outcome: 'A polished identity that makes documentation feel like a first-class product surface rather than a static support archive.', personality: ['Helpful', 'Calm', 'Polished', 'Developer-literate'], pillars: ['Invisible interaction', 'Developers deserve great design', 'Opinionated by default', 'Infinitely flexible when needed'], promise: 'Make the right knowledge beautiful, current, and easy to find.' },
  style: { borderRadius: 10, density: 'comfortable', grid: 'none', imageTreatment: 'natural', logoScale: 92 },
  tagline: 'The front door to your product.',
  typography: [{ family: 'Inter', role: 'Display', usage: 'Friendly product statements and documentation headlines' }, { family: 'Inter', role: 'Body', usage: 'Reading, navigation, and product UI' }, { family: 'Inter', role: 'Accent', usage: 'Card titles, callouts, and editorial emphasis' }, { family: 'Geist Mono', role: 'Code', usage: 'Code blocks, request examples, and API metadata' }],
  values: ['Taste', 'Iteration', 'Developer empathy', 'Flexibility'],
  voice: { avoid: ['Documentation as an afterthought', 'Dense technical language without a path', 'Customization presented as complexity'], phrases: ['Developers are users too.', 'Opinionated by default.', 'Built for the way your team works.'], principles: ['Helpful', 'Clear', 'Modern', 'Quietly opinionated'] },
  website: 'mintlify.com',
};

export const TAILWIND_BRAND_IDENTITY: BrandIdentity = {
  applications: [application('identity', 'Build anything', 'foundation', '1600 × 1000', 'The twin-wave mark and utility-first promise in a sky-blue technical field.'), application('logo', 'Tailwind logo family', 'foundation', 'Mark / logotype', 'Official cyan mark with slate or white logotype and protected clear space.'), application('playground', 'Playground', 'product', '1440 × 1024', 'Utilities, preview, responsive states, and generated CSS in one direct making surface.'), application('docs', 'Framework docs', 'developer', 'Responsive', 'Search, utilities, examples, and code presented with exceptional scanning rhythm.'), application('release', 'Release system', 'marketing', '16:9 / 4:5', 'Version launches assembled from wave motion, utility tokens, and product evidence.'), application('component', 'UI component', 'product', 'Responsive', 'A real interface example demonstrates expressive range without leaving HTML.'), application('community', 'Community build', 'social', '1:1', 'Contributor projects and techniques framed by cyan wave fields.'), application('workshop', 'Workshop kit', 'event', 'Deck / badge', 'A teaching system pairing live code, immediate output, and the utility vocabulary.')],
  assets: [asset('mark-dark', 'Official Tailwind CSS mark', '/brands/tailwind/logos/mark.svg', 'light'), asset('mark-light', 'Official Tailwind CSS mark', '/brands/tailwind/logos/mark.svg', 'dark'), asset('wordmark', 'Official Tailwind CSS logotype', '/brands/tailwind/logos/wordmark.svg', 'light'), asset('wordmark-light', 'Official Tailwind CSS white logotype', '/brands/tailwind/logos/wordmark-white.svg', 'dark'), asset('identity-field', 'Tailwind utility current', '/brands/tailwind/assets/utility-field.svg', 'any', 'background')],
  audiences: ['Frontend developers', 'Design engineers', 'Product teams', 'Component library authors'],
  builtIn: true,
  colors: [{ hex: '#0F172A', id: 'ink', name: 'Slate 900', role: 'Official logotype and primary type' }, { hex: '#FFFFFF', id: 'paper', name: 'White', role: 'Primary code and documentation surface' }, { hex: '#F8FAFC', id: 'muted', name: 'Slate 50', role: 'Quiet background' }, { hex: '#38BDF8', id: 'emphasis', name: 'Sky 400', role: 'Official mark and primary framework signal' }, { hex: '#7DD3FC', id: 'success', name: 'Sky 300', role: 'Soft wave and positive emphasis' }, { hex: '#E0F2FE', id: 'warning', name: 'Sky 100', role: 'Code selection and pale field' }, { hex: '#64748B', id: 'progress', name: 'Slate 500', role: 'Secondary type and metadata' }, { hex: '#020617', id: 'error', name: 'Slate 950', role: 'Dark documentation and campaign surface' }],
  contactEmail: 'support@tailwindcss.com',
  description: 'A cyan-and-slate developer identity for a utility-first CSS framework that lets teams build expressive interfaces directly in markup.',
  greetings: ['Compose', 'Style', 'Ship'],
  graphicSystem: { composition: 'Wave fields move behind tightly aligned code, token, and interface evidence.', description: 'The utility wave turns small composable classes into visible cumulative motion: two currents meeting, stacking, and accelerating.', device: 'The utility wave', imageDirection: 'Real interface examples, legible HTML, state comparisons, responsive crops, and community work.', pattern: 'wave', rules: ['Show the code and the result together', 'Use cyan as motion and emphasis', 'Let composition demonstrate composability', 'Never imply affiliation in third-party applications'] },
  id: 'tailwind', kind: 'example', mission: 'Make it fast and enjoyable to build any design directly in your markup.', motion: [{ curve: 'cubic-bezier(0.16, 1, 0.3, 1)', description: 'Two cyan currents assemble from utility-sized pieces and settle into a finished interface.', durationMs: 1000, id: 'utility-wave', name: 'Utility wave', previewPath: '' }], name: 'Tailwind CSS', positioning: 'Tailwind CSS is a utility-first framework for rapidly building custom user interfaces without leaving HTML.', products: ['Framework', 'Documentation', 'Playground', 'Tailwind UI'], proof: ['Utility-first workflow', 'Responsive variants', 'Design tokens', 'Component composition'], proofAssets: [], revision: REVISION, shortName: 'TW', socialHandle: '@tailwindcss', sourceNotes: ['Official Tailwind CSS brand asset page', 'Official Tailwind mark and logotype downloads', 'Trademark restrictions retained in Glyphfield legal documentation'],
  strategy: { challenge: 'Traditional CSS creates naming overhead, context switching, and drift between a design intent and the code that implements it.', concept: 'Small utilities become expressive systems through composition.', outcome: 'A framework identity that feels fast, technical, and open-ended while remaining instantly recognizable through its cyan current.', personality: ['Fast', 'Practical', 'Expressive', 'Precise'], pillars: ['Compose in markup', 'Constrain with tokens', 'Adapt through variants', 'Extract only when repetition earns it'], promise: 'Build the interface you mean without fighting the stylesheet.' },
  style: { borderRadius: 8, density: 'comfortable', grid: 'none', imageTreatment: 'natural', logoScale: 94 }, tagline: 'Build anything.', typography: [{ family: 'Inter', role: 'Display', usage: 'Framework statements and release headlines' }, { family: 'Inter', role: 'Body', usage: 'Documentation and interface explanation' }, { family: 'Inter', role: 'Accent', usage: 'Utility names and component labels' }, { family: 'Geist Mono', role: 'Code', usage: 'HTML, CSS, commands, and token values' }], values: ['Composability', 'Speed', 'Constraint', 'Craft'], voice: { avoid: ['Magic without showing the mechanism', 'Generic low-code language', 'Visual examples without the classes'], phrases: ['Build anything.', 'Rapidly build modern websites.', 'Style directly in your markup.'], principles: ['Practical', 'Direct', 'Code-forward', 'Enabling'] }, website: 'tailwindcss.com',
};

export const VITEPLUS_BRAND_IDENTITY: BrandIdentity = {
  applications: [application('identity', 'One toolchain', 'foundation', '1600 × 1000', 'The Vite+ bolt unifies a formerly fragmented frontend stack.'), application('logo', 'Vite+ logo system', 'foundation', 'Icon / logotype', 'Official gradient bolt and parenthetical toolchain mark on light and dark.'), application('terminal', 'Unified terminal', 'developer', '80 columns', 'Create, install, dev, check, test, build, and run through one vp vocabulary.'), application('stack', 'Toolchain diagram', 'product', '16:9', 'Runtime, packages, framework, linting, testing, and builds shown as one accelerated system.'), application('benchmark', 'Speed proof', 'marketing', '16:9', 'Measured performance paired with the exact task and tool being replaced.'), application('launch', 'Launch sequence', 'social', '1:1 / 4:5', 'Electric purple, mint energy, and terminal evidence introduce one capability at a time.'), application('docs', 'Toolchain guide', 'developer', 'Responsive', 'Installation and migration content organized around a single predictable command model.'), application('conference', 'Web toolchain keynote', 'event', 'Stage / deck', 'An isometric runtime stack and terminal narrative scaled for live explanation.')],
  assets: [asset('mark-dark', 'Official Vite+ icon', '/brands/viteplus/logos/mark.svg', 'light'), asset('mark-light', 'Official Vite+ icon', '/brands/viteplus/logos/mark.svg', 'dark'), asset('wordmark', 'Official Vite+ dark logotype', '/brands/viteplus/logos/wordmark-dark.svg', 'light'), asset('wordmark-light', 'Official Vite+ light logotype', '/brands/viteplus/logos/wordmark-light.svg', 'dark'), asset('identity-field', 'Vite+ convergence field', '/brands/viteplus/assets/convergence-field.svg', 'any', 'background')],
  audiences: ['Frontend developers', 'Platform teams', 'Framework maintainers', 'Large JavaScript organizations'], builtIn: true,
  colors: [{ hex: '#08060D', id: 'ink', name: 'Void', role: 'Primary type and terminal surface' }, { hex: '#FFFFFF', id: 'paper', name: 'White', role: 'Primary documentation field' }, { hex: '#F4F1FF', id: 'muted', name: 'Lilac mist', role: 'Quiet diagrams and code backgrounds' }, { hex: '#6254FE', id: 'emphasis', name: 'Vite violet', role: 'Official bolt and unified action' }, { hex: '#2BFDD2', id: 'success', name: 'Mint current', role: 'Success, acceleration, and energy' }, { hex: '#EDE6FF', id: 'warning', name: 'Electric haze', role: 'Glow and dimensional highlight' }, { hex: '#4E14FF', id: 'progress', name: 'Deep electric', role: 'Gradient depth and active process' }, { hex: '#17131F', id: 'error', name: 'Terminal', role: 'Dark product and campaign surface' }],
  contactEmail: 'hello@voidzero.dev', description: 'An electric developer identity for a unified toolchain that manages the JavaScript runtime, package manager, and frontend workflow through one fast interface.', greetings: ['Create', 'Check', 'Build'],
  graphicSystem: { composition: 'A dark terminal or isometric stack anchors the field while violet energy converges from many tools into one command.', description: 'The convergence field visualizes unification: multiple runtimes, packages, checks, and build paths bend toward one accelerated center.', device: 'The convergence field', imageDirection: 'Real terminal output, benchmarks, stack diagrams, framework marks, and granular build evidence.', pattern: 'burst', rules: ['One command remains the focal point', 'Use violet for convergence and mint for success', 'Show measurable performance with context', 'Keep the terminal output credible and copyable'] },
  id: 'viteplus', kind: 'example', mission: 'Give web developers one fast, coherent toolchain from environment setup to production build.', motion: [{ curve: 'cubic-bezier(0.2, 0.8, 0.2, 1)', description: 'Separate tool paths bend inward, lock into the vp command, and burst forward as one successful run.', durationMs: 850, id: 'converge', name: 'Toolchain converge', previewPath: '' }], name: 'Vite+', positioning: 'Vite+ unifies the runtime, package manager, and frontend toolchain so teams can create, install, develop, check, test, build, and run through one consistent flow.', products: ['Runtime manager', 'Package manager', 'Dev server', 'Formatter', 'Linter', 'Test runner', 'Bundler'], proof: ['One configuration', 'One command model', 'Fast at scale', 'Open-source foundations'], proofAssets: [], revision: REVISION, shortName: 'VP', socialHandle: '@vite_js', sourceNotes: ['Official Vite+ product site and command documentation', 'Official Vite+ icon and light/dark logotypes', 'Current performance and open-source positioning'],
  strategy: { challenge: 'Modern web development depends on a fragmented chain of runtimes, package managers, linters, formatters, test runners, dev servers, and bundlers with overlapping configuration.', concept: 'Many tools converge into one accelerated path.', outcome: 'A high-energy identity that makes unification tangible without hiding the open-source tools underneath.', personality: ['Fast', 'Unified', 'Technical', 'Electric'], pillars: ['One configuration', 'Consistent commands', 'Performance at scale', 'Open-source foundations'], promise: 'One toolchain from first command to production.' },
  style: { borderRadius: 12, density: 'comfortable', grid: 'none', imageTreatment: 'duotone', logoScale: 90 }, tagline: 'The unified toolchain for the web.', typography: [{ family: 'Inter', role: 'Display', usage: 'Large toolchain statements and performance proof' }, { family: 'Inter', role: 'Body', usage: 'Product explanation and documentation' }, { family: 'Inter', role: 'Accent', usage: 'Command families and framework labels' }, { family: 'Geist Mono', role: 'Code', usage: 'Every vp command, terminal state, and benchmark value' }], values: ['Speed', 'Coherence', 'Focus', 'Open source'], voice: { avoid: ['Speed claims without measurement', 'Unity that erases underlying tools', 'Abstract developer productivity clichés'], phrases: ['One toolchain.', 'Stay fast at scale.', 'Focus on shipping.'], principles: ['Direct', 'Measured', 'Developer-native', 'Energetic'] }, website: 'viteplus.dev',
};

export const CLOUDFLARE_BRAND_IDENTITY: BrandIdentity = {
  applications: [application('identity', 'A better Internet', 'foundation', '1600 × 1000', 'The orange cloud sits between users and origins as a visible network horizon.'), application('logo', 'Cloudflare logo family', 'foundation', 'Cloud / logotype', 'Official cloud-and-logotype system with orange, black, and white surface variants.'), application('network', 'Global network map', 'product', '16:9', 'Cities, traffic, security, compute, and data visualized as one connected operating layer.'), application('dashboard', 'Connectivity cloud', 'product', '1440 × 1024', 'Security, performance, reliability, developer, and network controls in a dense operational surface.'), application('workers', 'Developer platform', 'developer', 'Responsive', 'Code, deployment, runtime limits, observability, and edge topology shown together.'), application('research', 'Internet report', 'editorial', 'A4 / web', 'Large-scale network evidence and incident analysis with high information integrity.'), application('campaign', 'Internet signal', 'social', '1:1 / 16:9', 'Orange horizon bands carry launch, threat, performance, and reliability signals.'), application('summit', 'Network summit', 'event', 'Stage / badge', 'A global operating field that scales from attendee badge to panoramic stage.')],
  assets: [asset('mark-dark', 'Cloudflare cloud mark', '/brands/cloudflare/logos/mark.svg', 'light'), asset('mark-light', 'Cloudflare cloud mark / white', '/brands/cloudflare/logos/mark-white.svg', 'dark'), asset('wordmark', 'Cloudflare wordmark', '/brands/cloudflare/logos/wordmark.svg', 'light'), asset('wordmark-light', 'Cloudflare white wordmark', '/brands/cloudflare/logos/wordmark-white.svg', 'dark'), asset('identity-field', 'Cloudflare network horizon', '/brands/cloudflare/assets/network-horizon.svg', 'any', 'background')],
  audiences: ['Website and application teams', 'Security leaders', 'Network teams', 'Developers building at the edge'], builtIn: true,
  colors: [{ hex: '#404041', id: 'ink', name: 'Cloudflare charcoal', role: 'Primary type and infrastructure contrast' }, { hex: '#FFFFFF', id: 'paper', name: 'White', role: 'Primary documentation and product field' }, { hex: '#F7F7F5', id: 'muted', name: 'Fog', role: 'Network map and quiet surface' }, { hex: '#F38020', id: 'emphasis', name: 'Cloudflare orange', role: 'Official cloud, network path, and primary emphasis' }, { hex: '#FAAD3D', id: 'success', name: 'Sun', role: 'Cloud highlight and positive performance' }, { hex: '#FFF0DB', id: 'warning', name: 'Warm cloud', role: 'Soft orange data field' }, { hex: '#7A7A7A', id: 'progress', name: 'Graphite', role: 'Secondary network metadata' }, { hex: '#1D1D1F', id: 'error', name: 'Night network', role: 'Dark operational and campaign surface' }],
  contactEmail: 'press@cloudflare.com', description: 'An orange network identity for the connectivity cloud that protects, connects, and accelerates applications, networks, and people across a global edge.', greetings: ['Connect', 'Protect', 'Accelerate'],
  graphicSystem: { composition: 'A horizontal orange horizon divides the user-facing world from the network and origin layers beneath it.', description: 'The network horizon makes an invisible service visible: requests cross one orange edge where security, performance, compute, and reliability act together.', device: 'The network horizon', imageDirection: 'Global network maps, infrastructure diagrams, real traffic, operational dashboards, and human-scale Internet stories.', pattern: 'circuit', rules: ['The orange horizon indicates Cloudflare intervention', 'Use diagrams to clarify real architecture', 'Keep data labels technically accurate', 'Do not use marks outside documented trademark permissions'] },
  id: 'cloudflare', kind: 'example', mission: 'Help build a better Internet.', motion: [{ curve: 'cubic-bezier(0.22, 1, 0.36, 1)', description: 'Traffic travels to the orange horizon, resolves across the edge, and reaches the destination with visible protection and acceleration.', durationMs: 1200, id: 'edge-route', name: 'Edge route', previewPath: '' }], name: 'Cloudflare', positioning: 'Cloudflare is the connectivity cloud that helps organizations make applications and networks faster, more secure, more reliable, and easier to operate.', products: ['Application services', 'Zero Trust', 'Network services', 'Developer platform', 'R2 and data', 'AI'], proof: ['20% of websites protected', '335+ cities', '125+ countries', '42% of Fortune 500'], proofAssets: [], revision: REVISION, shortName: 'CF', socialHandle: '@Cloudflare', sourceNotes: ['Official Cloudflare press kit and logo page', 'Official Cloudflare product and company language', 'Official trademark guidance applies to all included reference assets'],
  strategy: { challenge: 'The Internet is globally distributed but organizations still manage security, performance, networking, compute, and data through fragmented infrastructure.', concept: 'One protective horizon across the Internet.', outcome: 'A clear infrastructure identity that turns invisible global work into an understandable connected system.', personality: ['Protective', 'Global', 'Technical', 'Optimistic'], pillars: ['Connect everything', 'Protect every request', 'Accelerate every experience', 'Simplify infrastructure'], promise: 'Make every connection faster, safer, and more reliable.' },
  style: { borderRadius: 4, density: 'compact', grid: 'none', imageTreatment: 'duotone', logoScale: 96 }, tagline: 'Connect, protect, and build everywhere.', typography: [{ family: 'Inter', role: 'Display', usage: 'Large network promises and report headlines' }, { family: 'Inter', role: 'Body', usage: 'Product UI, documentation, and explanatory narrative' }, { family: 'Inter', role: 'Accent', usage: 'Network statistics and city labels' }, { family: 'Geist Mono', role: 'Code', usage: 'Routes, requests, addresses, runtime state, and network metadata' }], values: ['Better Internet', 'Global reach', 'Technical integrity', 'Resilience'], voice: { avoid: ['Fear without actionable detail', 'Network abstractions that hide architecture', 'Unqualified scale claims'], phrases: ['Help build a better Internet.', 'Protect and accelerate.', 'Run everywhere.'], principles: ['Clear', 'Authoritative', 'Practical', 'Global'] }, website: 'cloudflare.com',
};

export const STRIPE_BRAND_IDENTITY: BrandIdentity = {
  applications: [application('identity', 'Economic infrastructure', 'foundation', '1600 × 1000', 'The Stripe wordmark sits inside a dimensional field of programmable money movement.'), application('logo', 'Stripe wordmark', 'foundation', 'Slate / blurple / white', 'Official wordmark colors only, with disciplined space and no unofficial symbol.'), application('payments', 'Payment surface', 'product', '1440 × 1024', 'Checkout, payments, subscriptions, tax, revenue, and risk presented as a coherent programmable platform.'), application('docs', 'Developer integration', 'developer', 'Responsive', 'API reference, code, request objects, and live payment evidence arranged for implementation speed.'), application('sessions', 'Stripe Sessions', 'event', 'Stage / badge', 'Dimensional gradients and precise product narratives for an economic infrastructure audience.'), application('report', 'Internet economy report', 'editorial', 'A4 / web', 'Data, business stories, and global economic signals in a rigorous editorial system.'), application('launch', 'Product launch', 'marketing', '16:9 / 4:5', 'A programmable gradient field reveals the specific workflow, object, or market unlocked.'), application('social', 'Economic signal', 'social', '1:1', 'Short evidence-led stories pairing bold type with restrained dimensional color.')],
  assets: [asset('mark-dark', 'Official Stripe blurple wordmark', '/brands/stripe/logos/wordmark-blurple.svg', 'light'), asset('mark-light', 'Official Stripe white wordmark', '/brands/stripe/logos/wordmark-white.svg', 'dark'), asset('wordmark', 'Official Stripe slate wordmark', '/brands/stripe/logos/wordmark-slate.svg', 'light'), asset('wordmark-light', 'Official Stripe white wordmark', '/brands/stripe/logos/wordmark-white.svg', 'dark'), asset('identity-field', 'Stripe programmable field', '/brands/stripe/assets/programmable-field.svg', 'any', 'background')],
  audiences: ['Developers', 'Internet businesses', 'Finance and revenue teams', 'Platforms and marketplaces'], builtIn: true,
  colors: [{ hex: '#061B31', id: 'ink', name: 'Stripe slate', role: 'Official wordmark and primary information color' }, { hex: '#FFFFFF', id: 'paper', name: 'White', role: 'Primary product and documentation surface' }, { hex: '#F6F9FC', id: 'muted', name: 'Cloud', role: 'Quiet product field and dimensional canvas' }, { hex: '#533AFD', id: 'emphasis', name: 'Blurple', role: 'Official wordmark option and primary product signal' }, { hex: '#00D4FF', id: 'success', name: 'Cyan', role: 'Dimensional gradient and positive movement' }, { hex: '#FF80A6', id: 'warning', name: 'Rose', role: 'Dimensional gradient and editorial contrast' }, { hex: '#7A73FF', id: 'progress', name: 'Periwinkle', role: 'Active data and atmospheric depth' }, { hex: '#0A2540', id: 'error', name: 'Deep slate', role: 'Dark product, editorial, and event surface' }],
  contactEmail: 'press@stripe.com', description: 'A precise, dimensional identity for the economic infrastructure platform that helps internet businesses accept payments, manage revenue, and build new business models.', greetings: ['Build', 'Sell', 'Grow'],
  graphicSystem: { composition: 'A precise product or economic object sits inside a deep programmable gradient field with clear typographic hierarchy.', description: 'The programmable field expresses money in motion: layered color, depth, and data bend around a concrete transaction, workflow, or economic signal.', device: 'The programmable field', imageDirection: 'Detailed product UI, real business environments, global economic stories, and dimensional abstract fields tied to a specific object.', pattern: 'flow', rules: ['Official wordmark is slate, blurple, or white only', 'Every gradient should frame a concrete economic object', 'Pair ambition with exact product evidence', 'Make developer implementation feel first-class'] },
  id: 'stripe', kind: 'example', mission: 'Increase the GDP of the internet.', motion: [{ curve: 'cubic-bezier(0.16, 1, 0.3, 1)', description: 'A payment object moves through layered color and resolves into a clear successful state.', durationMs: 1150, id: 'programmable-flow', name: 'Programmable flow', previewPath: '' }], name: 'Stripe', positioning: 'Stripe builds programmable economic infrastructure that businesses use to accept payments, manage revenue, automate financial operations, and create new internet business models.', products: ['Payments', 'Billing', 'Connect', 'Tax', 'Radar', 'Revenue', 'Issuing', 'Terminal'], proof: ['$1.4T+ processed in 2024', '100+ businesses processing $1B+ annually', 'Global payments infrastructure', 'Developer-first APIs'], proofAssets: [], revision: REVISION, shortName: 'S', socialHandle: '@stripe', sourceNotes: ['Official Stripe newsroom and media assets', 'Official slate, blurple, and white wordmark files', 'Stripe marks usage agreement applies to included reference assets'],
  strategy: { challenge: 'Internet businesses must assemble payments, billing, risk, tax, money movement, and financial operations across markets and legacy institutions.', concept: 'Make the movement of money programmable.', outcome: 'An ambitious but exact identity that connects developer implementation to a broader vision for internet economic growth.', personality: ['Precise', 'Ambitious', 'Global', 'Developer-first'], pillars: ['Programmable infrastructure', 'Global reach', 'Operational leverage', 'Economic possibility'], promise: 'Turn complex money movement into infrastructure a team can build on.' },
  style: { borderRadius: 12, density: 'comfortable', grid: 'none', imageTreatment: 'natural', logoScale: 90 }, tagline: 'Financial infrastructure for the internet.', typography: [{ family: 'Inter', role: 'Display', usage: 'Ambitious economic statements and product launches' }, { family: 'Inter', role: 'Body', usage: 'Product explanation, dashboard UI, and editorial narrative' }, { family: 'Times New Roman', role: 'Accent', usage: 'Economic reports and human editorial contrast' }, { family: 'Geist Mono', role: 'Code', usage: 'API objects, amounts, events, requests, and implementation metadata' }], values: ['Economic progress', 'Rigor', 'Leverage', 'Global scale'], voice: { avoid: ['Finance jargon without a user outcome', 'Grand vision without implementation evidence', 'Unofficial logo colors'], phrases: ['Increase the GDP of the internet.', 'Financial infrastructure for the internet.', 'Build new business models.'], principles: ['Ambitious', 'Exact', 'Developer-literate', 'Globally aware'] }, website: 'stripe.com',
};

export const BASEMENT_BRAND_IDENTITY: BrandIdentity = {
  applications: [
    application('identity', 'The studio, in one frame', 'foundation', '1600 × 1000', 'A blunt typographic statement, one engineered interruption, and enough space for the idea to land.'),
    application('type', 'Basement Grotesque specimen', 'foundation', 'A2 / responsive', 'The studio typeface is treated as an image: unapologetically heavy, repeated with control, and paired with quiet metadata.'),
    application('case-study', 'Case study opening', 'editorial', '1600 × 1000', 'The business problem and systemic idea lead before the visual reveal.'),
    application('project-index', 'Project index', 'product', '1440 × 1024', 'Selected work appears as an exact editorial sequence rather than a wall of interchangeable cards.'),
    application('lab', 'Basement Lab', 'developer', '16:9', 'A focused tool surface where the experiment is the hero and interface chrome stays out of its way.'),
    application('launch', 'Project launch', 'marketing', '4:5 / 16:9', 'One project-specific device carries the announcement across formats without becoming wallpaper.'),
    application('social', 'Studio dispatch', 'social', '1:1 / 4:5', 'Short, candid writing paired with one strong image, crop, or typographic move.'),
    application('deck', 'Project narrative', 'editorial', '16:9', 'Context, challenge, idea, system, application, and impact unfold as a paced argument.'),
    application('event', 'Basement session', 'event', 'Stage / badge', 'Oversized type and a single signal color scale from a small badge to a room.'),
    application('merch', 'Studio uniform', 'physical', 'Apparel / object', 'Black, off-white, and one direct studio line applied with the same restraint as the digital system.'),
  ],
  assets: [
    asset('mark-dark', 'Basement black mark', '/brands/basement/logos/mark-black.svg', 'light'),
    asset('mark-light', 'Basement white mark', '/brands/basement/logos/mark-white.svg', 'dark'),
    asset('wordmark', 'Basement black wordmark', '/brands/basement/logos/wordmark-black.svg', 'light'),
    asset('wordmark-light', 'Basement white wordmark', '/brands/basement/logos/wordmark-white.svg', 'dark'),
    asset('identity-field', 'Engineered interruption', '/brands/basement/assets/engineered-interruption.svg', 'any', 'background'),
  ],
  audiences: ['Ambitious technology companies', 'Culture-shaping founders', 'Product and brand leaders', 'Teams whose digital presence must perform'],
  builtIn: true,
  colors: [
    { hex: '#0A0A0A', id: 'ink', name: 'Basement black', role: 'Primary field, type, and uncompromising contrast' },
    { hex: '#F2F0E9', id: 'paper', name: 'Warm white', role: 'Open editorial field and reversed breathing room' },
    { hex: '#D9D6CD', id: 'muted', name: 'Concrete', role: 'Quiet structure, captions, and secondary surfaces' },
    { hex: '#F3A51B', id: 'emphasis', name: 'Signal amber', role: 'One deliberate signal, interaction, or focal interruption' },
    { hex: '#F2F0E9', id: 'success', name: 'Clear', role: 'Resolved state without adding another hue' },
    { hex: '#8E8A80', id: 'warning', name: 'Dust', role: 'Secondary information and material depth' },
    { hex: '#2B2B29', id: 'progress', name: 'Graphite', role: 'In-progress surfaces and tonal separation' },
    { hex: '#151513', id: 'error', name: 'Subfloor', role: 'Deep tonal extension and destructive contrast' },
  ],
  contactEmail: 'hello@basement.studio',
  description: 'A performance-minded studio identity built from heavy type, blunt contrast, precise pacing, and one memorable idea per application.',
  fonts: [
    {
      family: 'Basement Grotesque',
      fileName: 'BasementGrotesque-Black_v1.202.woff2',
      format: 'woff2',
      id: 'basement-grotesque-black',
      label: 'Basement Grotesque Black',
      path: '/fonts/basement-grotesque/BasementGrotesque-Black_v1.202.woff2',
      style: 'normal',
      weight: 800,
    },
    {
      family: 'Inter',
      fileName: 'Inter-Variable.ttf',
      format: 'truetype',
      id: 'inter-variable',
      label: 'Inter Variable',
      path: '/fonts/inter-variable.ttf',
      style: 'normal',
      weight: 400,
      weightMax: 900,
      weightMin: 100,
    },
    {
      family: 'Geist Mono',
      fileName: 'GeistMono-Variable.ttf',
      format: 'truetype',
      id: 'geist-mono-variable',
      label: 'Geist Mono Variable',
      path: '/fonts/geist-mono-variable.ttf',
      style: 'normal',
      weight: 400,
      weightMax: 900,
      weightMin: 100,
    },
  ],
  greetings: ['Make', 'Perform', 'Repeat'],
  graphicSystem: {
    composition: 'Let one oversized statement or image occupy the field. Anchor it with small factual metadata and interrupt the composition once—never everywhere.',
    description: 'The engineered interruption is a precise break in an otherwise severe system: a signal block, crop, gap, or motion event derived from the project idea.',
    device: 'The engineered interruption',
    imageDirection: 'Project-specific worlds, real product evidence, bold controlled crops, tactile light, and deliberate low-fidelity treatments. Effects must explain the subject instead of decorating it.',
    pattern: 'blocks',
    rules: ['One strong move per composition', 'Typography and negative space provide the structure', 'Derive the device from the project problem or product', 'Performance is part of the design', 'Use texture only when it adds material or solves banding'],
  },
  id: 'basement',
  kind: 'example',
  mission: 'Make digital identities and experiences that are impossible to ignore and engineered to perform.',
  motion: [
    { curve: 'cubic-bezier(0.22, 1, 0.36, 1)', description: 'A single interruption snaps into the field, holds, and exits before it becomes decoration.', durationMs: 900, id: 'signal-cut', name: 'Signal cut', previewPath: '' },
  ],
  name: 'Basement',
  positioning: 'Basement is an independent digital studio and branding partner for ambitious companies that need strategy, identity, product experience, and technical execution to behave as one system.',
  products: ['Brand strategy', 'Visual identity', 'Digital experience', 'Creative development', 'Studio tools'],
  proof: ['Vercel', 'Linear', 'ElevenLabs', 'Baseten', 'Krea', 'Cursor'],
  proofAssets: [],
  revision: REVISION,
  shortName: 'BSMNT',
  socialHandle: '@basementstudio',
  sourceNotes: [
    'Basement Studio — official site and capabilities',
    'ElevenLabs: Visual Rebrand for the Voice of AI — official case study',
    'Baseten: When Brand Meets Business — official case study',
    'Rox: Rebuilding the Digital Presence of a Top 100 AI Company — official case study',
    'Building a Unique Website for Basement Grotesque — official process article',
    'Mastering Color Gradients — official design article',
    'New Digital HQ, Part 1 — official development article',
  ],
  strategy: {
    challenge: 'Fast-moving technology companies often outgrow fragmented identity systems: the story, product, website, motion, and implementation stop feeling like the same company.',
    concept: 'Serious systems, playful expression—one sharp idea engineered through every surface.',
    outcome: 'A recognizable identity that gives the company cultural presence, gives its team reusable tools, and performs under real product and web constraints.',
    personality: ['Bold', 'Exact', 'Curious', 'Irreverent'],
    pillars: ['Find the business problem before the visual move', 'Build one ownable device', 'Treat code and performance as craft', 'Give teams tools they can remix', 'Let personality in without diluting the idea'],
    promise: 'Cool work that performs.',
  },
  style: { borderRadius: 0, density: 'spacious', grid: 'none', imageTreatment: 'monochrome', logoScale: 92 },
  tagline: 'Cool work that performs.',
  typography: [
    { family: 'Basement Grotesque', fontId: 'basement-grotesque-black', letterSpacing: -5, lineHeight: 0.88, role: 'Display', usage: 'Large, compressed statements with enough space to feel intentional', weight: 800 },
    { family: 'Inter', fontId: 'inter-variable', letterSpacing: -1, lineHeight: 1.45, role: 'Body', usage: 'Case-study narrative, product explanation, and supporting interface copy', weight: 450 },
    { family: 'Basement Grotesque', fontId: 'basement-grotesque-black', letterSpacing: -2, lineHeight: 0.92, role: 'Accent', usage: 'Short studio phrases, specimen moments, and project-specific interruptions', weight: 800 },
    { family: 'Geist Mono', fontId: 'geist-mono-variable', letterSpacing: 0, lineHeight: 1.45, role: 'Code', usage: 'Credits, project metadata, specifications, tools, and implementation evidence', weight: 450 },
  ],
  values: ['Ideas with a reason', 'Craft across disciplines', 'Performance by design', 'Serious work, human energy'],
  voice: {
    avoid: ['Agency superlatives without evidence', 'Long theory before the actual problem', 'Corporate filler', 'Explaining every visual gesture'],
    phrases: ['Cool work that performs.', 'One idea. Built all the way through.', 'The work should earn the attention.'],
    principles: ['Lead with the useful truth', 'Write like a confident person', 'Name the problem and the system', 'Keep the punchline short'],
  },
  website: 'basement.studio',
};

export const BUILT_IN_BRAND_IDENTITIES: readonly BrandIdentity[] = [
  STARTER_BRAND_IDENTITY,
  TEMPLATE_BRAND_IDENTITY,
  BASEMENT_BRAND_IDENTITY,
  GT_BRAND_IDENTITY,
  RAMP_BRAND_IDENTITY,
  MINTLIFY_BRAND_IDENTITY,
  TAILWIND_BRAND_IDENTITY,
  VITEPLUS_BRAND_IDENTITY,
  CLOUDFLARE_BRAND_IDENTITY,
  STRIPE_BRAND_IDENTITY,
];
