import {
  Aperture,
  Blend,
  BookMarked,
  BookOpen,
  Braces,
  Component,
  FileJson2,
  Frame,
  Image as ImageIcon,
  LayoutGrid,
  MonitorPlay,
  Palette,
  PanelsTopLeft,
  ScanLine,
  Settings2,
  Shapes,
  Type,
  Waves,
  type LucideIcon,
} from '@/components/ui/SolidIcons';

import type { StudioToolId } from '@/lib/studioCatalog';

export const STUDIO_TOOL_ICONS: Record<StudioToolId, LucideIcon> = {
  animation: Blend,
  backgrounds: ScanLine,
  blog: BookOpen,
  'brand-book': BookMarked,
  'brand-elements': LayoutGrid,
  buttons: Component,
  colors: Palette,
  'design-board': PanelsTopLeft,
  identity: Settings2,
  logo: Aperture,
  'logo-shader': Waves,
  lottie: FileJson2,
  material: Frame,
  opengraph: ImageIcon,
  partnership: Shapes,
  slides: MonitorPlay,
  surface: Shapes,
  terminal: Braces,
  typography: Type,
};
